In [89]:
import pandas as pd
data=pd.read_csv('Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [90]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [91]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [92]:
data.mainroad.value_counts()

mainroad
yes    468
no      77
Name: count, dtype: int64

In [93]:
data.mainroad=data.mainroad.map({"yes":1,"no":0})
data.guestroom=data.guestroom.map({"yes":1,"no":0})
data.basement=data.basement.map({"yes":1,"no":0})
data.hotwaterheating=data.hotwaterheating.map({"yes":1,"no":0})
data.airconditioning=data.airconditioning.map({"yes":1,"no":0})
data.prefarea=data.prefarea.map({"yes":1,"no":0})
data.furnishingstatus=data.furnishingstatus.map({"furnished":1,"unfurnished":0,"semi-furnished":2})

In [94]:
data.furnishingstatus.value_counts()
data.loc[:,"furnishingstatus"].value_counts()

furnishingstatus
2    227
0    178
1    140
Name: count, dtype: int64

In [95]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,2
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1

In [96]:
x= data.iloc[:,1:]
y=data.loc[:,:"price"]
y
# option 2:
# a = data.drop("price",axis = 1)
# a
# b = data.price
# b

        price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [97]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [98]:
x_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
175,9800,4,2,2,1,1,0,0,0,2,0,2
25,6540,4,2,2,1,1,1,0,1,2,1,1
253,3520,2,1,2,1,0,0,0,0,0,1,1
257,8250,3,1,1,1,0,0,0,0,0,0,1
431,3180,4,1,2,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
369,3600,2,1,1,1,0,0,0,0,0,0,1
320,4320,3,1,2,1,0,0,0,0,2,1,1
527,1836,2,1,1,0,0,1,0,0,0,0,2
125,15600,3,1,1,1,0,0,0,1,2,0,2
265,2880,3,1,2,1,0,0,0,0,0,1,2

In [99]:
y_train

       price
175  5250000
25   8540000
253  4515000
257  4480000
431  3290000
..       ...
369  3675000
320  4060000
527  2275000
125  5943000
265  4403000

[381 rows x 1 columns]

In [100]:
y_test

       price
482  2940000
314  4095000
383  3570000
487  2870000
43   7700000
..       ...
26   8463000
212  4893000
282  4270000
226  4690000
99   6265000

[164 rows x 1 columns]

In [101]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [102]:
model.fit(x_train,y_train)

LinearRegression()

In [103]:
model.predict(x_test)

array([[ 2643688.64149161],
       [ 3859348.78874555],
       [ 5730627.48102526],
       [ 3827438.52424499],
       [ 6766875.41577844],
       [ 6730710.32316336],
       [ 3596564.77481856],
       [ 3075533.50443743],
       [ 5520441.06589971],
       [ 3125199.02746381],
       [ 4829932.40955298],
       [ 2136891.82159399],
       [ 4371266.62091605],
       [ 4724570.25010246],
       [ 6543164.5658446 ],
       [ 2406068.91604462],
       [ 7147914.70068885],
       [ 6585910.36772905],
       [ 5282810.55591119],
       [ 4470022.24115468],
       [ 2596709.0988355 ],
       [ 1958784.85228497],
       [ 6004907.82023877],
       [ 5602975.66565994],
       [ 6542097.01668916],
       [ 6288584.42636222],
       [ 3825831.14723936],
       [ 3723359.68855966],
       [ 3796428.43761258],
       [ 3742717.90785411],
       [ 4210885.19680247],
       [ 4773810.58445008],
       [ 5686700.28389722],
       [ 5524770.03354721],
       [ 7282810.71521415],
       [ 4871144.48996974],
       [ 6462485.11591827],
       [ 2099513.09357825],
       [ 5073566.30436028],
       [ 5682496.20807365],
       [ 4973004.92719895],
       [ 5453420.4119225 ],
       [ 2920485.65371902],
       [ 6477283.39891603],
       [ 5807787.35060219],
       [ 7712067.55365214],
       [ 8356255.63347548],
       [ 6300614.22551077],
       [ 3613204.03959714],
       [ 5107633.203705  ],
       [ 3452520.21726448],
       [ 5801315.07288728],
       [ 4098921.83593993],
       [ 4588721.47498385],
       [ 2871853.65831978],
       [ 5854528.71865912],
       [ 5079767.4324888 ],
       [ 3738442.14274981],
       [ 3929541.34649548],
       [ 4583554.8799044 ],
       [ 4751044.01993008],
       [ 4964070.93671769],
       [ 5354103.76765579],
       [ 3496040.56491157],
       [ 4340598.41595706],
       [ 6624623.8741858 ],
       [ 2892206.15483869],
       [ 2562765.84183932],
       [ 2486159.94547128],
       [ 7344444.71316192],
       [ 4243699.66299968],
       [ 6639099.7878766 ],
       [ 5998246.6110754 ],
       [ 3459691.80877502],
       [ 2541709.70703514],
       [ 3472232.81872899],
       [ 3247178.34132132],
       [ 5265428.5072689 ],
       [ 9945143.39355888],
       [ 4990829.36068646],
       [ 7389447.91588824],
       [ 5099899.02343466],
       [ 3897902.69082021],
       [ 2711730.00489747],
       [ 4514487.98558269],
       [ 2321061.21324605],
       [ 5054789.42345412],
       [10296125.65636269],
       [ 5583048.92654705],
       [ 3124818.87131827],
       [ 5775316.34872264],
       [ 3430689.42260014],
       [ 6170236.01628642],
       [ 6167712.21800972],
       [ 4154071.18488859],
       [ 3671593.32197897],
       [ 3491802.38545571],
       [ 6690254.05250573],
       [ 4992170.7546357 ],
       [ 5014432.51307353],
       [ 5096512.43607507],
       [ 3758836.07604391],
       [ 4681794.91812449],
       [ 4440527.69017047],
       [ 6952716.30959188],
       [ 4360429.6045018 ],
       [ 4216513.50195449],
       [ 3210126.28550484],
       [ 5891339.15156396],
       [ 2796426.42383896],
       [ 4550017.10463722],
       [ 4759062.55192695],
       [ 4044999.6836583 ],
       [ 2973974.84767105],
       [ 3014085.40842108],
       [ 5680152.1814085 ],
       [ 3349949.21497385],
       [ 2195072.859068  ],
       [ 5135109.47748485],
       [ 4763936.03438728],
       [ 7648753.5644766 ],
       [ 4359310.24488211],
       [ 4990357.57550404],
       [ 4249880.45113758],
       [ 7274959.25959225],
       [ 3411815.22422667],
       [ 4750762.91484676],
       [ 4897409.45168339],
       [ 5587879.95470314],
       [ 4460302.52037422],
       [ 5160244.62947531],
       [ 4881276.25466232],
       [ 6754850.26341666],
       [ 4704362.02229929],
       [ 3572831.96640045],
       [ 4802765.05517657],
       [ 4384853.53275358],
       [ 3080593.37962398],
       [ 7353609.12149625],
       [ 4970692.55054916],
       [ 5559806.32251608],
       [ 8536726.51606993],
       [ 6276284.40937208],
       [ 3600647.93736464],
       [ 3691758.09128799],
       [ 6968930.46564468],
       [ 6492962.34119626],
       [ 4458719.71605272],
       [ 5878889.43826273],
       [ 4635581.71277682],
       [ 3667981.71713986],
       [ 3375466.46809012],
       [ 3609252.364254  ],
       [ 6453598.59552251],
       [ 7617689.53919442],
       [ 3018727.37037116],
       [ 3899630.12642644],
       [ 4455821.04574248],
       [ 3049935.16303915],
       [ 8306707.61333383],
       [ 6625053.05827095],
       [ 4032359.93151222],
       [ 5865009.95235097],
       [ 5815779.55373835]])

In [104]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score , mean_squared_error
r2_score(y_test,y_pred)

0.7359925296419539

In [108]:
mean_squared_error(y_test,y_pred)

769757564338.5887

In [109]:
import joblib
joblib.dump(model,'house.pkl')

['house.pkl']

In [110]:
import joblib
house =joblib.load('house.pkl')
house.predict([[9960,4,2,3,1,0,1,0,1,2,1,0]])

c:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[9027238.46325902]])

In [111]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.1-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.23-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in C:\Users\arshd\AppData\Roaming\Python\Python314\site-packages (from kagglehub) (26.1)
Collecting pyyaml (from kagglehub)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in C:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (2.33.1)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.22->kagglehub)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2026.4.22)
Requirement already satisfied: colorama in C:\Users\arshd\AppData\Roaming\Python\Python314\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.1-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.23-py3-none-any.whl (217 kB)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, pyyaml, protobuf, kagglesdk, kagglehub

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [pyyaml]
   -------- ------------------------------- 1/5 [pyyaml]
   -------- ------------------------------- 1/5 [pyyaml]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ---------------- ----------------------- 2/5 [protobuf]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   -------------------------------- ------- 4/5 [kagglehub]
   -------------------------------- ------- 4/5 [kagglehub]
   -------------------------------- ------- 4/5 [kagglehub]
   -------------------------------- ------- 4/5 [kagglehub]
   ---------------------------------------- 5/5 [kagglehub]

Successfully installed kagglehub-1.0.1 kagglesdk-0.1.23 protobuf-7.34.1 pyyaml-6.0.3 tqdm-4.67.3

  WARNING: The script tqdm.exe is installed in 'C:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip